# #####################################################################
#                 MapProxy example configuration
# #####################################################################
#
# This is _not_ a runnable configuration, but it contains most
# available options in meaningful combinations.
#
# Use this file in addition to the documentation to see where and how
# things can be configured.


services:
  demo:
  wms:
    # only offer WMS 1.1.1
    versions: ['1.1.1', '1.3.0']
    # supported SRS for this WMS
    srs: ['EPSG:4326', 'EPSG:3857']
    # force the layer extents (BBOX) to be displayed in this SRS
    bbox_srs: ['EPSG:4326']
    # limit the supported image formats.
    image_formats: ['image/jpeg', 'image/png', 'image/gif', 'image/GeoTIFF', 'image/tiff']
    # return an OGC service exception when one or more sources return errors
    # or no response at all (e.g. timeout)
    on_source_errors: raise

    # some WMS clients do not send all required parameters in feature info
    # requests, MapProxy ignores these errors unless you set strict to true.
    strict: true

    # list of feature info types the server should offer
    featureinfo_types: ['text', 'html', 'xml']

    md:
      # metadata used in capabilities documents
      title: Brecht maps
      abstract: A proxy to the world
      online_resource: http://ameleon.be
      contact:
        person: Brecht Van Maldergem
        position: GIS Passionate
        organization:
        address:
        city:
        postcode:
        country: Belgium
        phone:
        email: brecht.vanmaldergem@gmail.com
      access_constraints:
        Insert license and copyright information for this service.
      fees: 'None'
  tms:
    use_grid_names: true

layers:
  - name: CartoWeb
    title: CartoWeb
    sources: [cartoweb_cache]
  - name: osm
    title: Open Streetmap Tiles
    sources: [osm_cache] #this layer should use the osm_cache (defined below) as it's source.

caches:
  cartoweb_cache:
    #sources: [cartoweb_wms] 
    sources: [] # You can set the sources to an empty list, if you use an existing MBTiles file and do not have a source.
    grids: [webmercator_grid]
    meta_size: [5,5]
    meta_buffer: 20
    concurrent_tile_creators: 2
    cache:
      type: mbtiles
      filename: /mapproxy/cartoweb.mbtiles
  osm_cache:
    sources: [osm_tiles] #here you set what source data (defined below) you want to cache
    format: image/png
  
sources:
  cartoweb_wms:
     type: wms
     req:
       url: https://cartoweb.wms.ngi.be/service?
       layers: topo
     coverage:
       bbox: [2.5141,49.4751,6.4442,51.5645]   #BE
       srs: EPSG:4326
    
  osm_tiles:
     #the osm_tiles source refers to the openstreetmap.org tiles. These will be downloaded upon request (if not already cached) and served by MapProxy
     type: tile
     url: http://c.tile.openstreetmap.org/%(tms_path)s.%(format)s
     grid: webmercator_grid #the grid to use for the osm tiles. This is really important. It is specified below.

grids:
  webmercator_grid:
    base: GLOBAL_MERCATOR
    srs: 'EPSG:3857'
    origin: nw 

globals:
  cache:
    # where to store the cached images
    base_dir: './cache_data'
    # where to store lockfiles
    lock_dir: './cache_data/locks'
    meta_size: [6, 6]
    meta_buffer: 20
    # where to store lockfiles for tile creation
    tile_lock_dir: './cache_data/tile_locks'
  http:
    ssl_no_cert_checks: true

  # image/transformation options
  image:
      resampling_method: bilinear
      jpeg_quality: 90